{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.loadBalancerName }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-group-attributes: {{ .Values.ingress.targetGroupAttributes }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.listenPorts }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect }}
    alb.ingress.kubernetes.io/ssl-policy: {{ .Values.ingress.sslPolicy }}
spec:
  rules:
  - host: {{ .Values.ingress.rules.host }}
    http:
      paths:
      {{- range .Values.ingress.rules.paths }}
      - pathType: {{ .pathType }}
        path: {{ .path }}
        backend:
          service:
            name: {{ .service.name }}
            port: 
              number: {{ .service.port }}
      {{- end }}
{{- end }}
