apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::339712755995:role/AmazonEKSLoadBalancerControllerRole
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
